admin:
  port: 9990

telemetry:
- kind: io.l5d.influxdb
- kind: io.l5d.recentRequests
  sampleRate: 1.0
  capacity: 200
- kind: io.l5d.tracelog
  sampleRate: 0.2
  level: TRACE  

# telemetry:
# - kind: io.l5d.prometheus

namers:
- kind: io.l5d.fs
  rootDir: disco

routers:
- protocol: http  
  label: core
  dtab: |
    /svc# => /#/io.l5d.fs;
    /core => /svc#/core;
    /ui => /svc#/ui;
  servers:
  - port: 8000