admin:
  port: 9990

telemetry:
- kind: io.l5d.influxdb
- kind: io.l5d.recentRequests
  sampleRate: 1.0
  capacity: 200
- kind: io.l5d.tracelog
  sampleRate: 0.2
  level: TRACE  

namers:
- kind: io.l5d.fs
  rootDir: disco

routers:
- protocol: http
  dtab: |
    /svc/ui   => /svc/ui;
    /svc/core => /svc/core;
    /svc      => /#/io.l5d.fs;
  dstPrefix: /svc
  identifier:
    kind: io.l5d.path
    segments: 1
  servers:
  - port: 8000
  client:
    failureAccrual:
      kind: io.l5d.consecutiveFailures
      failures: 5
      backoff:
        kind: constant
        ms: 10000