# core business
core:
  image: maven:3.3.9-jdk-8
  working_dir: /core
  command: mvn spring-boot:run
  ports:
    - "8082:8082"
  volumes:
    - ../core:/core
    - ~/.m2:/root/.m2
  net: "host"

# user interface
ui:
  image: maven:3.3.9-jdk-8
  working_dir: /ui          
  command: mvn spring-boot:run 
  ports:
    - "9000:9000"
  volumes:
    - ../ui:/ui
    - ~/.m2:/root/.m2
  net: "host"

# data base
db:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - ./data:/var/lib/postgresql
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=core
  net: "host"

# linkerd
linkerd:
  image: buoyantio/linkerd:1.3.3
  ports:
    - "9990:9990"
    - "8000:8000"
  volumes:
    - ../linkerd/disco:/io.buoyant/linkerd/1.3.3/disco 
    - ../linkerd/config/linkerd.yaml:/config.yaml
  command:
    - /config.yaml
  net: "host"

# influxdb
# influxdb:
#   image: influxdb:1.2.2

# telegraf
# telegraf:
  # image: telegraf:1.2.1
  # volumes:
  # - ../linkerd/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

# grafana
# grafana:
  # image: grafana/grafana:3.1.1
  # ports:
  # - 3000:3000
  # volumes:
  # - ../linkerd/grafana/grafana.json:/usr/share/grafana/public/dashboards/home.json:ro
  # environment:
  #   - GF_AUTH_ANONYMOUS_ENABLED=true
  #   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

# grafana_bootstrap
# grafana_bootstrap:
  # image: buoyantio/slow_cooker:1.1.0
  # entrypoint: /bin/sh
  # volumes:
  # - ../linkerd/grafana/grafana-bootstrap.sh:/grafana-bootstrap.sh:ro
  # command: >
  #   -c '/grafana-bootstrap.sh'